package vista;

import Dao.DaoCargo;
import Dao.DaoEmpleado;
import Dao.DaoMateria;
import Dao.DaoPermiso;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.cargo;
import modelo.empleado;
import modelo.materias;
import modelo.permisos;

/**
 *
 * @author almed
 */
public class MenuPrincipal extends javax.swing.JFrame {
    cargo cr = new cargo();
    DaoCargo daoC = new DaoCargo();
    DefaultTableModel modeloCargo= new DefaultTableModel();
    
    materias m = new materias();
    DaoMateria daoM = new DaoMateria();
    DefaultTableModel modeloMateria= new DefaultTableModel();
    
    int auxCi = 0;
    empleado em = new empleado();
    DaoEmpleado daoEm = new DaoEmpleado();
    DefaultTableModel modeloEmpleado= new DefaultTableModel();
    
    permisos pe = new permisos();
    DaoPermiso daoPe = new DaoPermiso();
    DefaultTableModel modeloPermiso= new DefaultTableModel();
    
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        listar();
        listarMateria();
        listarEmpleado();
        btnEnviarMateria.setEnabled(false);
        btnEnviarCargo.setEnabled(false);
        btnEnviarCi.setEnabled(false);
    }
    private void listar(){
        List<cargo> lista = daoC.Listar();
        modeloCargo=(DefaultTableModel)tablacargos.getModel();
        Object[] ob = new Object[2];
        for(int i=0; i< lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNombre();
            modeloCargo.addRow(ob);
        }
        tablacargos.setModel(modeloCargo);
    }

    private void listarMateria(){
        List<materias> lista = daoM.Listar();
        modeloMateria=(DefaultTableModel)tablaMateria.getModel();
        Object[] ob = new Object[2];
        for(int i=0; i< lista.size();i++){
            ob[0]=lista.get(i).getIdMateria();
            ob[1]=lista.get(i).getNomMateria();
            modeloMateria.addRow(ob);
        }
        tablaMateria.setModel(modeloMateria);
    }
    
    private void listarEmpleado(){
        try{
            DefaultTableModel modelo;
            modelo = daoEm.listar();
            tablaempleado.setModel(modelo);
        }catch(Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnCargos = new javax.swing.JButton();
        btnPermisos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        panel = new javax.swing.JTabbedPane();
        phome = new javax.swing.JPanel();
        pusuarios = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        pempleados = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtci = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnomempleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtapempleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtidmateriaempleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmateriaempleado = new javax.swing.JTextField();
        btnBuscarMateria = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtidcargoempleado = new javax.swing.JTextField();
        txtcargoempleado = new javax.swing.JTextField();
        btnBuscarCargo = new javax.swing.JButton();
        btnregistrarempleado = new javax.swing.JButton();
        btnModificarEmpleado = new javax.swing.JButton();
        btnBuscarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaempleado = new javax.swing.JTable();
        btnEnviarCi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pmaterias = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMateria = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtidmateria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmateria = new javax.swing.JTextField();
        btnregistrarMateria = new javax.swing.JButton();
        btneditarMateria = new javax.swing.JButton();
        btnbuscarMateria = new javax.swing.JButton();
        btneliminarMateria = new javax.swing.JButton();
        btnEnviarMateria = new javax.swing.JButton();
        pcargo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminarCargos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacargos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnEnviarCargo = new javax.swing.JButton();
        ppermisos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbotipopermiso = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtdescrip = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtnompermiso = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtciPermisos = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtnomPermisos = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtapPermisos = new javax.swing.JTextField();
        btnBuscarCi = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnCargarImagen = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnMaterias.setText("Materias");
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });

        btnCargos.setText("Cargos");
        btnCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargosActionPerformed(evt);
            }
        });

        btnPermisos.setText("Permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPermisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        phome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout phomeLayout = new javax.swing.GroupLayout(phome);
        phome.setLayout(phomeLayout);
        phomeLayout.setHorizontalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        phomeLayout.setVerticalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        panel.addTab("Home", phome);

        pusuarios.setBackground(new java.awt.Color(255, 255, 255));
        pusuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Nombre");

        jLabel19.setText("Usuario");

        jLabel20.setText("Constraseña");

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pusuariosLayout = new javax.swing.GroupLayout(pusuarios);
        pusuarios.setLayout(pusuariosLayout);
        pusuariosLayout.setHorizontalGroup(
            pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pusuariosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pusuariosLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pusuariosLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pusuariosLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(846, Short.MAX_VALUE))
        );
        pusuariosLayout.setVerticalGroup(
            pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pusuariosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(591, Short.MAX_VALUE))
        );

        panel.addTab("Usuarios", pusuarios);

        pempleados.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado"));

        jLabel5.setText("CI:");

        jLabel6.setText("Nombre:");

        txtnomempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomempleadoActionPerformed(evt);
            }
        });

        jLabel7.setText("Apellido:");

        jLabel8.setText("Telefono:");

        jLabel9.setText("Correo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomempleado)
                            .addComponent(txtci)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapempleado)
                            .addComponent(txtcorreo)
                            .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtapempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Materia"));

        jLabel10.setText("Sigla:");

        jLabel11.setText("Nombre:");

        txtmateriaempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmateriaempleadoActionPerformed(evt);
            }
        });

        btnBuscarMateria.setText("jButton1");
        btnBuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtidmateriaempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmateriaempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnBuscarMateria)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtidmateriaempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtmateriaempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarMateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo"));

        jLabel12.setText("ID:");

        jLabel13.setText("Nombre:");

        txtcargoempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcargoempleadoActionPerformed(evt);
            }
        });

        btnBuscarCargo.setText("jButton5");
        btnBuscarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidcargoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcargoempleado)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(btnBuscarCargo)
                .addGap(68, 68, 68))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtidcargoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtcargoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarCargo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnregistrarempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible.png"))); // NOI18N
        btnregistrarempleado.setText("Registrar");
        btnregistrarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarempleadoActionPerformed(evt);
            }
        });

        btnModificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapiz-3d.png"))); // NOI18N
        btnModificarEmpleado.setText("Editar");
        btnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmpleadoActionPerformed(evt);
            }
        });

        btnBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnBuscarEmpleado.setText("Buscar");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        btnEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        tablaempleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaempleadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaempleado);

        btnEnviarCi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar (1).png"))); // NOI18N
        btnEnviarCi.setText("Enviar");
        btnEnviarCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCiActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout pempleadosLayout = new javax.swing.GroupLayout(pempleados);
        pempleados.setLayout(pempleadosLayout);
        pempleadosLayout.setHorizontalGroup(
            pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pempleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pempleadosLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pempleadosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(pempleadosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pempleadosLayout.createSequentialGroup()
                                        .addComponent(btnModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminarEmpleado))
                                    .addGroup(pempleadosLayout.createSequentialGroup()
                                        .addComponent(btnregistrarempleado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEnviarCi)
                                        .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pempleadosLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2))
                                            .addGroup(pempleadosLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jButton4)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pempleadosLayout.setVerticalGroup(
            pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pempleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pempleadosLayout.createSequentialGroup()
                        .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pempleadosLayout.createSequentialGroup()
                                .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnregistrarempleado)
                                    .addComponent(btnBuscarEmpleado)
                                    .addComponent(btnEnviarCi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButton4)))
                            .addComponent(jButton2))
                        .addGroup(pempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarEmpleado)
                            .addComponent(btnEliminarEmpleado)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.addTab("Empleados", pempleados);

        pmaterias.setBackground(new java.awt.Color(255, 255, 255));

        tablaMateria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaMateria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMateriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMateria);

        jLabel3.setText("Sigla : ");

        txtidmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidmateriaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        btnregistrarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible.png"))); // NOI18N
        btnregistrarMateria.setText("Registrar");
        btnregistrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarMateriaActionPerformed(evt);
            }
        });

        btneditarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapiz-3d.png"))); // NOI18N
        btneditarMateria.setText("Editar");
        btneditarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarMateriaActionPerformed(evt);
            }
        });

        btnbuscarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnbuscarMateria.setText("Buscar");
        btnbuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarMateriaActionPerformed(evt);
            }
        });

        btneliminarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btneliminarMateria.setText("Eliminar");
        btneliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarMateriaActionPerformed(evt);
            }
        });

        btnEnviarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar (1).png"))); // NOI18N
        btnEnviarMateria.setText("Enviar");
        btnEnviarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pmateriasLayout = new javax.swing.GroupLayout(pmaterias);
        pmaterias.setLayout(pmateriasLayout);
        pmateriasLayout.setHorizontalGroup(
            pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmateriasLayout.createSequentialGroup()
                .addGroup(pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pmateriasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidmateria, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtmateria)))
                    .addGroup(pmateriasLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btneditarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnregistrarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnbuscarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btneliminarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnEnviarMateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        pmateriasLayout.setVerticalGroup(
            pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmateriasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtidmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pmateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addComponent(btnregistrarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneditarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbuscarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneliminarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarMateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pmateriasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.addTab("Materias", pmaterias);

        pcargo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre: ");

        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible.png"))); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapiz-3d.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        btnEliminarCargos.setText("Eliminar");
        btnEliminarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCargosActionPerformed(evt);
            }
        });

        tablacargos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablacargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablacargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacargos);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEnviarCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar (1).png"))); // NOI18N
        btnEnviarCargo.setText("Enviar");
        btnEnviarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pcargoLayout = new javax.swing.GroupLayout(pcargo);
        pcargo.setLayout(pcargoLayout);
        pcargoLayout.setHorizontalGroup(
            pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcargoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarCargos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnviarCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        pcargoLayout.setVerticalGroup(
            pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcargoLayout.createSequentialGroup()
                .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(pcargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pcargoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        panel.addTab("Cargos", pcargo);

        ppermisos.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Del Permiso"));

        jLabel14.setText("Nombre ");

        jLabel15.setText("Descripcion ");

        cbotipopermiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Con Licencia", "Sin Licencia", " " }));
        cbotipopermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipopermisoActionPerformed(evt);
            }
        });

        txtdescrip.setColumns(20);
        txtdescrip.setRows(5);
        jScrollPane4.setViewportView(txtdescrip);

        jLabel18.setText("Tipo de Permiso");

        jLabel21.setText("Fecha: ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbotipopermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(txtnompermiso))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtnompermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbotipopermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(68, 68, 68))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Del Empleado"));

        jLabel17.setText("CI");

        txtciPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciPermisosActionPerformed(evt);
            }
        });

        jLabel22.setText("Nombre:");

        jLabel23.setText("Apellido: ");

        btnBuscarCi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar (1).png"))); // NOI18N
        btnBuscarCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(4, 4, 4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtciPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtapPermisos)
                            .addComponent(txtnomPermisos))
                        .addGap(41, 41, 41)))
                .addComponent(btnBuscarCi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtciPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnomPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtapPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBuscarCi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de la Imagen"));

        btnCargarImagen.setText("Cargar Imagen");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(btnCargarImagen)
                .addGap(20, 20, 20))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCargarImagen)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapiz-3d.png"))); // NOI18N
        jButton3.setText("Editar");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jButton5.setText("Buscar");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        jButton6.setText("Eliminar");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf (1).png"))); // NOI18N
        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppermisosLayout = new javax.swing.GroupLayout(ppermisos);
        ppermisos.setLayout(ppermisosLayout);
        ppermisosLayout.setHorizontalGroup(
            ppermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppermisosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(ppermisosLayout.createSequentialGroup()
                        .addGroup(ppermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ppermisosLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ppermisosLayout.setVerticalGroup(
            ppermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppermisosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppermisosLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66))
                    .addGroup(ppermisosLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ppermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6)
                            .addComponent(jButton1)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel.addTab("Permisos", ppermisos);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        panel.addTab("Asistencia", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        panel.setSelectedComponent(pusuarios);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
                panel.setSelectedComponent(pempleados);

    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        // TODO add your handling code here:
                panel.setSelectedComponent(pmaterias);

    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargosActionPerformed
        // TODO add your handling code here:
                panel.setSelectedComponent(pcargo);

    }//GEN-LAST:event_btnCargosActionPerformed

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        // TODO add your handling code here:
                panel.setSelectedComponent(ppermisos);
    }//GEN-LAST:event_btnPermisosActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        cr.setNombre(txtcargo.getText());
        if(daoC.insertar(cr)){
            JOptionPane.showMessageDialog(null, "Cargo Registrado Con Exito");
            limpiarDatosCargo();
            limpiarTablaCargo();
            listar();
        }else{
            JOptionPane.showMessageDialog(null, "Error al Registrar el Cargo ");
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void tablacargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacargosMouseClicked
        // TODO add your handling code here:
        int fila=tablacargos.getSelectedRow();
        txtid.setText(tablacargos.getValueAt(fila,0).toString());
        txtcargo.setText(tablacargos.getValueAt(fila,1).toString());
    }//GEN-LAST:event_tablacargosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila=tablacargos.getSelectedRow();
        if(fila==-1){
        JOptionPane.showMessageDialog(null, "Seleccione Un Cargo");
        }else{
            cr.setId(Integer.parseInt(txtid.getText()));
            cr.setNombre(txtcargo.getText());
            if(daoC.editar(cr)){
                JOptionPane.showMessageDialog(null, "Se Modifico Con Exito");
                limpiarDatosCargo();
                limpiarTablaCargo();
                listar();
            }else{
                JOptionPane.showMessageDialog(null, "Error al Modificar");                
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCargosActionPerformed
        // TODO add your handling code here:
        if(!txtid.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(rootPane,"Seguro de Eliminar el Cargo","Confirmar",2);
            if(confirmacion==0){
                cr.setId(Integer.parseInt(txtid.getText()));
                daoC.eliminar(cr);
                limpiarDatosCargo();
                limpiarTablaCargo();
                listar();
            }
        }
    }//GEN-LAST:event_btnEliminarCargosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        cr.setId(Integer.parseInt(txtid.getText()));
        if(daoC.Buscar(cr)){
            txtid.setText(cr.getId()+"");
            txtcargo.setText(cr.getNombre());
        }else{
            JOptionPane.showMessageDialog(null, "El Cargo no Existe "); 
            txtid.setText("");
            txtcargo.setText("");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtidmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidmateriaActionPerformed
         //TODO add your handling code here:
    }//GEN-LAST:event_txtidmateriaActionPerformed

    private void btnregistrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarMateriaActionPerformed
    // TODO add your handling code here:
    String idMateria = txtidmateria.getText();
    String nomMateria = txtmateria.getText();

    if (idMateria.isEmpty() || nomMateria.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
    } else {
        m.setIdMateria(idMateria);
        m.setNomMateria(nomMateria);

        if (daoM.insertar(m)) {
            JOptionPane.showMessageDialog(null, "Materia Registrada Con Exito");
            limpiarDatosMateria();
            limpiarTablaMateria();
            listarMateria();
        } else {
            JOptionPane.showMessageDialog(null, "Error al Registrar la Materia");
        }
    }
    }//GEN-LAST:event_btnregistrarMateriaActionPerformed

    private void btneditarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarMateriaActionPerformed
        // TODO add your handling code here:
        int fila=tablaMateria.getSelectedRow();
        if(fila==-1){
        JOptionPane.showMessageDialog(null, "Seleccione Un Cargo");
        }else{
            m.setIdMateria(txtidmateria.getText());
            m.setNomMateria(txtmateria.getText()); 
            if(daoM.editar(m)){
                JOptionPane.showMessageDialog(null, "Se Modifico Con Exito");
                limpiarDatosMateria();
                limpiarTablaMateria();
                listarMateria();
            }else{
                JOptionPane.showMessageDialog(null, "Error al Modificar");                
            }
        }
        
    }//GEN-LAST:event_btneditarMateriaActionPerformed

    private void tablaMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMateriaMouseClicked
        // TODO add your handling code here:
        int fila=tablaMateria.getSelectedRow();
        txtidmateria.setText(tablaMateria.getValueAt(fila,0).toString());
        txtmateria.setText(tablaMateria.getValueAt(fila,1).toString());
    }//GEN-LAST:event_tablaMateriaMouseClicked

    private void btnbuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarMateriaActionPerformed
        // TODO add your handling code here:
        m.setIdMateria(txtidmateria.getText());
        if(daoM.Buscar(m)){
            txtidmateria.setText(m.getIdMateria());
            txtmateria.setText(m.getNomMateria());
        }else{
            JOptionPane.showMessageDialog(null, "La Materia no Existe "); 
            txtidmateria.setText("");
            txtmateria.setText("");
        }
       
    }//GEN-LAST:event_btnbuscarMateriaActionPerformed

    private void btneliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarMateriaActionPerformed
        // TODO add your handling code here:
            if(!txtidmateria.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(rootPane, "¿Seguro de eliminar la Materia?","Confirmar",2);
            if(confirmacion==0){
                m.setIdMateria(txtidmateria.getText());
                daoM.eliminar(m);
                limpiarDatosMateria();
                limpiarTablaMateria();
                listarMateria();                
            }
        }
    }//GEN-LAST:event_btneliminarMateriaActionPerformed

    private void txtnomempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomempleadoActionPerformed

    private void txtmateriaempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmateriaempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmateriaempleadoActionPerformed

    private void txtcargoempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcargoempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcargoempleadoActionPerformed

    private void btnregistrarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarempleadoActionPerformed
        // TODO add your handling code here:
            try {
            // Obtener el texto del campo de texto y convertirlo a entero
            int ci = Integer.parseInt(txtci.getText());
            int telefono = Integer.parseInt(txttelefono.getText());
            // Asignar el valor al objeto cr
            em.setCi(ci);
            em.setTelefono(telefono);
            em.setNombre(txtnomempleado.getText());
            em.setApellido(txtapempleado.getText());
            em.setCorreo(txtcorreo.getText());
            em.setIdCargos(Integer.parseInt(txtidcargoempleado.getText()));
            em.setIdMateria(txtidmateriaempleado.getText());

        } catch (NumberFormatException e) {
            // Manejo de error si el texto no puede ser convertido a un entero
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(daoEm.insertar(em)){
            JOptionPane.showMessageDialog(null,"Empleado Registrado con exito");
            limpiarDatosEmpleado();
            limpiarTablaEmpleado();
            listarEmpleado();
        }else{
            JOptionPane.showMessageDialog(null,"Error al Registrar ");
        }
    }//GEN-LAST:event_btnregistrarempleadoActionPerformed

    private void btnEnviarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMateriaActionPerformed
        // TODO add your handling code here:
        txtidmateriaempleado.setText(txtidmateria.getText());
        txtmateriaempleado.setText(txtmateria.getText());
        btnEnviarMateria.setEnabled(false);
        panel.setSelectedComponent(pempleados);
    }//GEN-LAST:event_btnEnviarMateriaActionPerformed

    private void btnBuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMateriaActionPerformed
        // TODO add your handling code here:
        btnEnviarMateria.setEnabled(true);
        panel.setSelectedComponent(pmaterias);
        
    }//GEN-LAST:event_btnBuscarMateriaActionPerformed

    private void btnEnviarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCargoActionPerformed
        // TODO add your handling code here:
        txtidcargoempleado.setText(txtid.getText());
        txtcargoempleado.setText(txtcargo.getText());
        btnEnviarCargo.setEnabled(false);
        panel.setSelectedComponent(pempleados);
    }//GEN-LAST:event_btnEnviarCargoActionPerformed

    private void btnBuscarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCargoActionPerformed
        // TODO add your handling code here:
        panel.setSelectedComponent(pcargo);
        btnEnviarCargo.setEnabled(true);
    }//GEN-LAST:event_btnBuscarCargoActionPerformed

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed
        // TO   DO add your handling code here:
       int fila = tablaempleado.getSelectedRow();
       if(fila==-1){    
           JOptionPane.showMessageDialog(null,"Seleccione un usuario");
       }else{
           em.setCi(Integer.parseInt(txtci.getText()));
           em.setNombre(txtnomempleado.getText());
           em.setApellido(txtapempleado.getText());
           em.setTelefono(Integer.parseInt(txttelefono.getText()));
           em.setCorreo(txtcorreo.getText());
           em.setIdCargos(Integer.parseInt(txtidcargoempleado.getText()));
           em.setIdMateria(txtidmateriaempleado.getText());     
           if(daoEm.editar(em, auxCi)){
                JOptionPane.showMessageDialog(null,"Se Modifico Con Exito");
                limpiarDatosEmpleado();
                limpiarTablaEmpleado();
                listarEmpleado();
           }else{
               JOptionPane.showMessageDialog(null,"Error al modificar");
               
           }
       }        
        
    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void tablaempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaempleadoMouseClicked
        // TODO add your handling code here:
        int fila=tablaempleado.getSelectedRow();
        
        txtci.setText               (tablaempleado.getValueAt(fila,0).toString());
        txtnomempleado.setText      (tablaempleado.getValueAt(fila,1).toString());
        txtapempleado.setText       (tablaempleado.getValueAt(fila,2).toString());
        txttelefono.setText         (tablaempleado.getValueAt(fila,3).toString());
        txtcorreo.setText           (tablaempleado.getValueAt(fila,4).toString());
        txtidcargoempleado.setText  (tablaempleado.getValueAt(fila,5).toString());
        txtcargoempleado.setText    (tablaempleado.getValueAt(fila,6).toString());
        txtidmateriaempleado.setText(tablaempleado.getValueAt(fila,7).toString());
        txtmateriaempleado.setText  (tablaempleado.getValueAt(fila,8).toString());
        auxCi=Integer.parseInt(txtci.getText());
    }//GEN-LAST:event_tablaempleadoMouseClicked

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
         // TODO add your handling code here:
        em.setCi(Integer.parseInt(txtci.getText()));
        
        if(daoEm.Buscar(em)){
        txtci.setText(em.getCi()+"");
        txtnomempleado.setText(em.getNombre()+"");
        txtapempleado.setText(em.getApellido()+"");
        txttelefono.setText(em.getTelefono()+"");
        txtcorreo.setText(em.getCorreo()+"");
        txtidcargoempleado.setText(em.getIdCargos()+"");
        txtidmateriaempleado.setText(em.getIdMateria()+"");
        
        cr.setId(Integer.parseInt(txtidcargoempleado.getText()));
        daoC.Buscar(cr);
        txtcargoempleado.setText(cr.getNombre());
        
        m.setIdMateria(txtidmateriaempleado.getText());
        daoM.Buscar(m);
        txtmateriaempleado.setText(m.getNomMateria());
        }else{
            JOptionPane.showMessageDialog(null, "El Empleado no Existe "); 
            limpiarDatosEmpleado();
        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
            if(!txtci.getText().isEmpty()){
            int confirmacion=JOptionPane.showConfirmDialog(rootPane, "¿Seguro de eliminar el EMPLEADO?","Confirmar",2);
            if(confirmacion==0){
                em.setCi(Integer.parseInt(txtci.getText()));
                daoEm.eliminar(em);
                limpiarDatosEmpleado();
                limpiarTablaEmpleado();
                listarEmpleado();                
            }
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

///AREA DE LOS PERMISOS     
    private void cbotipopermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipopermisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbotipopermisoActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnBuscarCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCiActionPerformed
        // TODO add your handling code here:
        btnEnviarCi.setEnabled(true);
        panel.setSelectedComponent(pempleados);
    }//GEN-LAST:event_btnBuscarCiActionPerformed

    private void txtciPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciPermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciPermisosActionPerformed

    
//BOTOON DE LA PARTE DE EMPLEADOS     
    private void btnEnviarCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCiActionPerformed
        // TODO add your handling code here:
        txtciPermisos.setText(txtci.getText());
        txtnomPermisos.setText(txtnomempleado.getText());
        txtapPermisos.setText(txtapempleado.getText());
        btnEnviarCi.setEnabled(false);
        panel.setSelectedComponent(ppermisos);
    }//GEN-LAST:event_btnEnviarCiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        
        pe.setTipo_permiso(cbotipopermiso.getSelectedItem().toString());
    }//GEN-LAST:event_btnRegistrarActionPerformed
     
     
     
     
    void limpiarDatosCargo(){
        txtid.setText("");
        txtcargo.setText("");
    }
    void limpiarTablaCargo(){
        for(int i=0;i<modeloCargo.getRowCount();i++){
            modeloCargo.removeRow(i);
            i=0-1;
        }
    }

    void limpiarDatosMateria(){
        txtidmateria.setText("");
        txtmateria.setText("");
    }
    void limpiarTablaMateria(){
        for(int i=0;i<modeloMateria.getRowCount();i++){
            modeloMateria.removeRow(i);
            i=0-1;
        }
    }
    
    void limpiarDatosEmpleado(){
        txtci.setText("");
        txtnomempleado.setText("");
        txtapempleado.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
        txtidcargoempleado.setText("");
        txtcargoempleado.setText("");
        txtidmateriaempleado.setText("");
        txtmateriaempleado.setText("");
    }
    void limpiarTablaEmpleado(){
    for(int i=0; i<modeloEmpleado.getRowCount();i++){
        modeloEmpleado.removeRow(i);
        i=0-1;
    } 
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            FlatArcOrangeIJTheme.setup();
        }catch(Exception ex){
            System.err.println("Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCargo;
    private javax.swing.JButton btnBuscarCi;
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnBuscarMateria;
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.JButton btnCargos;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminarCargos;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEnviarCargo;
    private javax.swing.JButton btnEnviarCi;
    private javax.swing.JButton btnEnviarMateria;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnbuscarMateria;
    private javax.swing.JButton btneditarMateria;
    private javax.swing.JButton btneliminarMateria;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnregistrarMateria;
    private javax.swing.JButton btnregistrarempleado;
    private javax.swing.JComboBox<String> cbotipopermiso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel pcargo;
    private javax.swing.JPanel pempleados;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel pmaterias;
    private javax.swing.JPanel ppermisos;
    private javax.swing.JPanel pusuarios;
    private javax.swing.JTable tablaMateria;
    private javax.swing.JTable tablacargos;
    private javax.swing.JTable tablaempleado;
    private javax.swing.JTextField txtapPermisos;
    private javax.swing.JTextField txtapempleado;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcargoempleado;
    private javax.swing.JTextField txtci;
    private javax.swing.JTextField txtciPermisos;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextArea txtdescrip;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidcargoempleado;
    private javax.swing.JTextField txtidmateria;
    private javax.swing.JTextField txtidmateriaempleado;
    private javax.swing.JTextField txtmateria;
    private javax.swing.JTextField txtmateriaempleado;
    private javax.swing.JTextField txtnomPermisos;
    private javax.swing.JTextField txtnomempleado;
    private javax.swing.JTextField txtnompermiso;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
